import { describe, expect, test } from "vitest";

import { createUserId, generateUserId } from "./user-id";

// Generated by Copilot

describe("createUserId", () => {
  test("should create valid user ID", () => {
    const result = createUserId("user-123");

    expect(result._unsafeUnwrap()).toBe("user-123");
  });

  test("should reject empty string", () => {
    const result = createUserId("");

    expect(result._unsafeUnwrapErr()).toBe("InvalidUserId");
  });
});

describe("generateUserId", () => {
  test("should generate unique user IDs", () => {
    const id1 = generateUserId();
    const id2 = generateUserId();

    expect(id1).not.toBe(id2);
  });
});
