import { describe, expect, test } from "vitest";

import { createAccountId } from "./account-id";

// Generated by Copilot

describe("createAccountId", () => {
  test("should create valid account ID", () => {
    const result = createAccountId("account-123");

    expect(result._unsafeUnwrap()).toBe("account-123");
  });

  test("should reject empty string", () => {
    const result = createAccountId("");

    expect(result._unsafeUnwrapErr()).toBe("AccountId cannot be empty");
  });
});
