import { describe, expect, test } from "vitest";

import { createCalendar } from "./calendar";

// Generated by Copilot

describe("createCalendar", () => {
  test("should create valid calendar", () => {
    const calendarData = {
      id: "calendar-123",
      name: "My Calendar",
      owner_id: "user-123",
    };

    const result = createCalendar(calendarData);

    const calendar = result._unsafeUnwrap();
    expect(calendar).toMatchObject({
      id: "calendar-123",
      name: "My Calendar",
      owner_id: "user-123",
    });
  });

  test("should reject invalid data", () => {
    const calendarData = {
      id: "calendar-123",
      name: "",
      owner_id: "",
    };

    const result = createCalendar(calendarData);

    const error = result._unsafeUnwrapErr();
    expect(error.errors).toHaveLength(2);
  });
});
