import { describe, expect, test } from "vitest";

import { createCalendarId, generateCalendarId } from "./id";

// Generated by Copilot

describe("createCalendarId", () => {
  test("should create calendar ID from string", () => {
    const id = "test-calendar-id";
    const result = createCalendarId(id);

    expect(result._unsafeUnwrap()).toBe(id);
  });

  test("should handle empty string", () => {
    const result = createCalendarId("");

    expect(result._unsafeUnwrap()).toBe("");
  });
});

describe("generateCalendarId", () => {
  test("should generate unique IDs", () => {
    const id1 = generateCalendarId();
    const id2 = generateCalendarId();

    expect(id1).not.toBe(id2);
  });
});
